import { Ingredient } from "../types/Ingredient";

const popularIngredients:Ingredient[] = [
    { id: 1, name: 'Chicken Breast', foodGroup: 'Meat' },
    { id: 2, name: 'Eggs', foodGroup: 'Dairy' },
    { id: 3, name: 'Tomatoes', foodGroup: 'Vegetable' },
    { id: 4, name: 'Olive Oil', foodGroup: 'Oil' },
    { id: 5, name: 'Garlic', foodGroup: 'Vegetable' },
    { id: 6, name: 'Onions', foodGroup: 'Vegetable' },
    { id: 7, name: 'Milk', foodGroup: 'Dairy' },
    { id: 8, name: 'Cheddar Cheese', foodGroup: 'Dairy' },
    { id: 9, name: 'Beef', foodGroup: 'Meat' },
    { id: 10, name: 'Carrots', foodGroup: 'Vegetable' },
    { id: 11, name: 'Potatoes', foodGroup: 'Vegetable' },
    { id: 12, name: 'Butter', foodGroup: 'Dairy' },
    { id: 13, name: 'Spinach', foodGroup: 'Vegetable' },
    { id: 14, name: 'Lettuce', foodGroup: 'Vegetable' },
    { id: 15, name: 'Chicken Thighs', foodGroup: 'Meat' },
    { id: 16, name: 'Parmesan Cheese', foodGroup: 'Dairy' },
    { id: 17, name: 'Yogurt', foodGroup: 'Dairy' },
    { id: 18, name: 'Pork', foodGroup: 'Meat' },
    { id: 19, name: 'Bell Peppers', foodGroup: 'Vegetable' },
    { id: 20, name: 'Garlic Powder', foodGroup: 'Spice' },
    { id: 21, name: 'Ground Beef', foodGroup: 'Meat' },
    { id: 22, name: 'Flour', foodGroup: 'Grain' },
    { id: 23, name: 'Sugar', foodGroup: 'Sweetener' },
    { id: 24, name: 'Rice', foodGroup: 'Grain' },
    { id: 25, name: 'Salt', foodGroup: 'Spice' },
    { id: 26, name: 'Black Pepper', foodGroup: 'Spice' },
    { id: 27, name: 'Lemon', foodGroup: 'Fruit' },
    { id: 28, name: 'Apples', foodGroup: 'Fruit' },
    { id: 29, name: 'Bananas', foodGroup: 'Fruit' },
    { id: 30, name: 'Olives', foodGroup: 'Fruit' },
    { id: 31, name: 'Tomato Sauce', foodGroup: 'Condiment' },
    { id: 32, name: 'Chicken Broth', foodGroup: 'Condiment' },
    { id: 33, name: 'Cucumber', foodGroup: 'Vegetable' },
    { id: 34, name: 'Avocado', foodGroup: 'Fruit' },
    { id: 35, name: 'Sour Cream', foodGroup: 'Dairy' },
    { id: 36, name: 'Cilantro', foodGroup: 'Herb' },
    { id: 37, name: 'Basil', foodGroup: 'Herb' },
    { id: 38, name: 'Parsley', foodGroup: 'Herb' },
    { id: 39, name: 'Thyme', foodGroup: 'Herb' },
    { id: 40, name: 'Oregano', foodGroup: 'Herb' },
    { id: 41, name: 'Chicken Wings', foodGroup: 'Meat' },
    { id: 42, name: 'Pasta', foodGroup: 'Grain' },
    { id: 43, name: 'Cinnamon', foodGroup: 'Spice' },
    { id: 44, name: 'Ginger', foodGroup: 'Spice' },
    { id: 45, name: 'Soy Sauce', foodGroup: 'Condiment' },
    { id: 46, name: 'Honey', foodGroup: 'Sweetener' },
    { id: 47, name: 'Sesame Oil', foodGroup: 'Oil' },
    { id: 48, name: 'Cornstarch', foodGroup: 'Starch' },
    { id: 49, name: 'Balsamic Vinegar', foodGroup: 'Condiment' },
    { id: 50, name: 'Bell Peppers', foodGroup: 'Vegetable' },
    { id: 51, name: 'Green Beans', foodGroup: 'Vegetable' },
    { id: 52, name: 'Zucchini', foodGroup: 'Vegetable' },
    { id: 53, name: 'Eggplant', foodGroup: 'Vegetable' },
    { id: 54, name: 'Peas', foodGroup: 'Vegetable' },
    { id: 55, name: 'Shrimp', foodGroup: 'Seafood' },
    { id: 56, name: 'Salmon', foodGroup: 'Seafood' },
    { id: 57, name: 'Tuna', foodGroup: 'Seafood' },
    { id: 58, name: 'Mayo', foodGroup: 'Condiment' },
    { id: 59, name: 'Mustard', foodGroup: 'Condiment' },
    { id: 60, name: 'Bread', foodGroup: 'Grain' },
    { id: 61, name: 'Bagels', foodGroup: 'Grain' },
    { id: 62, name: 'Tortillas', foodGroup: 'Grain' },
    { id: 63, name: 'Oats', foodGroup: 'Grain' },
    { id: 64, name: 'Yogurt', foodGroup: 'Dairy' },
    { id: 65, name: 'Cheese', foodGroup: 'Dairy' },
    { id: 66, name: 'Cream Cheese', foodGroup: 'Dairy' },
    { id: 67, name: 'Cream', foodGroup: 'Dairy' },
    { id: 68, name: 'Cottage Cheese', foodGroup: 'Dairy' },
    { id: 69, name: 'Ricotta Cheese', foodGroup: 'Dairy' },
    { id: 70, name: 'Mozzarella Cheese', foodGroup: 'Dairy' },
    { id: 71, name: 'Feta Cheese', foodGroup: 'Dairy' },
    { id: 72, name: 'Gorgonzola', foodGroup: 'Dairy' },
    { id: 73, name: 'Gruyere Cheese', foodGroup: 'Dairy' },
    { id: 74, name: 'Parmigiano-Reggiano', foodGroup: 'Dairy' },
    { id: 75, name: 'Gouda Cheese', foodGroup: 'Dairy' },
    { id: 76, name: 'Ricotta', foodGroup: 'Dairy' },
    { id: 77, name: 'Brie Cheese', foodGroup: 'Dairy' },
    { id: 78, name: 'Pita Bread', foodGroup: 'Grain' },
    { id: 79, name: 'Wheat Flour', foodGroup: 'Grain' },
    { id: 80, name: 'Corn Flour', foodGroup: 'Grain' },
    { id: 81, name: 'Coconut Flour', foodGroup: 'Grain' },
    { id: 82, name: 'Whole Wheat Flour', foodGroup: 'Grain' },
    { id: 83, name: 'Almond Flour', foodGroup: 'Grain' },
    { id: 84, name: 'Rice Flour', foodGroup: 'Grain' },
    { id: 85, name: 'Quinoa', foodGroup: 'Grain' },
    { id: 86, name: 'Barley', foodGroup: 'Grain' },
    { id: 87, name: 'Farro', foodGroup: 'Grain' },
    { id: 88, name: 'Bulgur', foodGroup: 'Grain' },
    { id: 89, name: 'Polenta', foodGroup: 'Grain' },
    { id: 90, name: 'Grapes', foodGroup: 'Fruit' },
    { id: 91, name: 'Oranges', foodGroup: 'Fruit' },
    { id: 92, name: 'Strawberries', foodGroup: 'Fruit' },
    { id: 93, name: 'Blueberries', foodGroup: 'Fruit' },
    { id: 94, name: 'Raspberries', foodGroup: 'Fruit' },
    { id: 95, name: 'Pineapple', foodGroup: 'Fruit' },
    { id: 96, name: 'Peaches', foodGroup: 'Fruit' },
    { id: 97, name: 'Plums', foodGroup: 'Fruit' },
    { id: 98, name: 'Avocados', foodGroup: 'Fruit' },
    { id: 99, name: 'Limes', foodGroup: 'Fruit' },
    { id: 100, name: 'Kiwifruit', foodGroup: 'Fruit' },
    { id: 101, name: 'Chili Peppers', foodGroup: 'Spice' },
    { id: 102, name: 'Paprika', foodGroup: 'Spice' },
    { id: 103, name: 'Turmeric', foodGroup: 'Spice' },
    { id: 104, name: 'Cumin', foodGroup: 'Spice' },
    { id: 105, name: 'Coriander', foodGroup: 'Spice' },
    { id: 106, name: 'Nutmeg', foodGroup: 'Spice' },
    { id: 107, name: 'Cardamom', foodGroup: 'Spice' },
    { id: 108, name: 'Cloves', foodGroup: 'Spice' },
    { id: 109, name: 'Bay Leaves', foodGroup: 'Spice' },
    { id: 110, name: 'Saffron', foodGroup: 'Spice' },
    { id: 111, name: 'Tarragon', foodGroup: 'Herb' },
    { id: 112, name: 'Rosemary', foodGroup: 'Herb' },
    { id: 113, name: 'Dill', foodGroup: 'Herb' },
    { id: 114, name: 'Chives', foodGroup: 'Herb' },
    { id: 115, name: 'Mint', foodGroup: 'Herb' },
    { id: 116, name: 'Rosemary', foodGroup: 'Herb' },
    { id: 117, name: 'Sage', foodGroup: 'Herb' },
    { id: 118, name: 'Fennel', foodGroup: 'Vegetable' },
    { id: 119, name: 'Leeks', foodGroup: 'Vegetable' },
    { id: 120, name: 'Celery', foodGroup: 'Vegetable' },
    { id: 121, name: 'Artichokes', foodGroup: 'Vegetable' },
    { id: 122, name: 'Asparagus', foodGroup: 'Vegetable' },
    { id: 123, name: 'Mushrooms', foodGroup: 'Vegetable' },
    { id: 124, name: 'Sweet Potatoes', foodGroup: 'Vegetable' },
    { id: 125, name: 'Squash', foodGroup: 'Vegetable' },
    { id: 126, name: 'Cauliflower', foodGroup: 'Vegetable' },
    { id: 127, name: 'Broccoli', foodGroup: 'Vegetable' },
    { id: 128, name: 'Brussels Sprouts', foodGroup: 'Vegetable' },
    { id: 129, name: 'Pumpkin', foodGroup: 'Vegetable' },
    { id: 130, name: 'Beets', foodGroup: 'Vegetable' },
    { id: 131, name: 'Ginger Root', foodGroup: 'Spice' },
    { id: 132, name: 'Basil Leaves', foodGroup: 'Herb' },
    { id: 133, name: 'Serrano Peppers', foodGroup: 'Spice' },
    { id: 134, name: 'Chili Flakes', foodGroup: 'Spice' },
    { id: 135, name: 'Mustard Seeds', foodGroup: 'Spice' },
    { id: 136, name: 'Fenugreek', foodGroup: 'Spice' },
    { id: 137, name: 'Tamarind', foodGroup: 'Fruit' },
    { id: 138, name: 'Coconut', foodGroup: 'Fruit' },
    { id: 139, name: 'Dates', foodGroup: 'Fruit' },
    { id: 140, name: 'Apricots', foodGroup: 'Fruit' },
    { id: 141, name: 'Pears', foodGroup: 'Fruit' },
    { id: 142, name: 'Plums', foodGroup: 'Fruit' },
    { id: 143, name: 'Cherries', foodGroup: 'Fruit' },
    { id: 144, name: 'Raisins', foodGroup: 'Fruit' },
    { id: 145, name: 'Sunflower Seeds', foodGroup: 'Seed' },
    { id: 146, name: 'Pumpkin Seeds', foodGroup: 'Seed' },
    { id: 147, name: 'Chia Seeds', foodGroup: 'Seed' },
    { id: 148, name: 'Flax Seeds', foodGroup: 'Seed' },
    { id: 149, name: 'Walnuts', foodGroup: 'Nut' },
    { id: 150, name: 'Almonds', foodGroup: 'Nut' },
    { id: 151, name: 'Pecans', foodGroup: 'Nut' },
    { id: 152, name: 'Cashews', foodGroup: 'Nut' },
    { id: 153, name: 'Pine Nuts', foodGroup: 'Nut' },
    { id: 154, name: 'Hazelnuts', foodGroup: 'Nut' },
    { id: 155, name: 'Brazil Nuts', foodGroup: 'Nut' },
    { id: 156, name: 'Macadamia Nuts', foodGroup: 'Nut' },
    { id: 157, name: 'Sesame Seeds', foodGroup: 'Seed' },
    { id: 158, name: 'Poppy Seeds', foodGroup: 'Seed' },
    { id: 159, name: 'Coconut Oil', foodGroup: 'Oil' },
    { id: 160, name: 'Avocado Oil', foodGroup: 'Oil' },
    { id: 161, name: 'Canola Oil', foodGroup: 'Oil' },
    { id: 162, name: 'Vegetable Oil', foodGroup: 'Oil' },
    { id: 163, name: 'Sunflower Oil', foodGroup: 'Oil' },
    { id: 164, name: 'Grapeseed Oil', foodGroup: 'Oil' },
    { id: 165, name: 'Safflower Oil', foodGroup: 'Oil' },
    { id: 166, name: 'Sesame Oil', foodGroup: 'Oil' },
    { id: 167, name: 'Red Wine Vinegar', foodGroup: 'Condiment' },
    { id: 168, name: 'White Wine Vinegar', foodGroup: 'Condiment' },
    { id: 169, name: 'Rice Vinegar', foodGroup: 'Condiment' },
    { id: 170, name: 'Apple Cider Vinegar', foodGroup: 'Condiment' },
    { id: 171, name: 'Dijon Mustard', foodGroup: 'Condiment' },
    { id: 172, name: 'Hot Sauce', foodGroup: 'Condiment' },
    { id: 173, name: 'Soy Sauce', foodGroup: 'Condiment' },
    { id: 174, name: 'Worcestershire Sauce', foodGroup: 'Condiment' },
    { id: 175, name: 'Hoisin Sauce', foodGroup: 'Condiment' },
    { id: 176, name: 'BBQ Sauce', foodGroup: 'Condiment' },
    { id: 177, name: 'Teriyaki Sauce', foodGroup: 'Condiment' },
    { id: 178, name: 'Maple Syrup', foodGroup: 'Sweetener' },
    { id: 179, name: 'Agave Syrup', foodGroup: 'Sweetener' },
    { id: 180, name: 'Stevia', foodGroup: 'Sweetener' },
    { id: 181, name: 'Molasses', foodGroup: 'Sweetener' },
    { id: 182, name: 'Brown Sugar', foodGroup: 'Sweetener' },
    { id: 183, name: 'Powdered Sugar', foodGroup: 'Sweetener' },
    { id: 184, name: 'Corn Syrup', foodGroup: 'Sweetener' },
    { id: 185, name: 'Honey', foodGroup: 'Sweetener' },
    { id: 186, name: 'Agave Nectar', foodGroup: 'Sweetener' },
    { id: 187, name: 'Dates Syrup', foodGroup: 'Sweetener' },
    { id: 188, name: 'Peanut Butter', foodGroup: 'Nut' },
    { id: 189, name: 'Almond Butter', foodGroup: 'Nut' },
    { id: 190, name: 'Cashew Butter', foodGroup: 'Nut' },
    { id: 191, name: 'Sunflower Butter', foodGroup: 'Nut' },
    { id: 192, name: 'Tahini', foodGroup: 'Nut' },
    { id: 193, name: 'Coconut Milk', foodGroup: 'Dairy' },
    { id: 194, name: 'Almond Milk', foodGroup: 'Dairy' },
    { id: 195, name: 'Soy Milk', foodGroup: 'Dairy' },
    { id: 196, name: 'Cashew Milk', foodGroup: 'Dairy' },
    { id: 197, name: 'Oat Milk', foodGroup: 'Dairy' },
    { id: 198, name: 'Rice Milk', foodGroup: 'Dairy' },
    { id: 199, name: 'Kefir', foodGroup: 'Dairy' },
    { id: 200, name: 'Buttermilk', foodGroup: 'Dairy' }
  ];
  
  export default popularIngredients;
  